name: zenn_trends
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  fl_chart: ^0.65.0
  url_launcher: ^6.2.1
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  device_preview: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.3.3
  freezed: ^2.4.5
  flutter_secure_storage: ^9.0.0
  firebase_auth: ^4.14.0
  google_sign_in: ^6.1.6
  lottie: ^2.7.0
  http: ^1.1.0
  flutter_markdown: ^0.6.18+2
  html2md: ^1.3.1
  dotenv: ^4.2.0
  dart_openai: ^5.0.0
  flex_color_scheme: ^7.3.1
  settings_ui: ^2.0.2
  modal_bottom_sheet: ^3.0.0-pre
  animated_toggle_switch: ^0.8.0
  fluttertoast: ^8.2.4
  flutter_easyloading: ^3.0.5
  mockito: ^5.4.3
  sticky_headers: ^0.3.0+2
  skeleton_text: ^3.0.1
  line_awesome_flutter: ^2.0.0
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/privacy_policy/ja.md

flutter_icons:
 android: true
 ios: true
 image_path: "assets/images/app_icon.png"
 remove_alpha_ios: true