name: zenn_trends
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.16.0
  flutter_dotenv: ^5.1.0
  cloud_firestore: ^4.9.2
  fl_chart: ^0.63.0
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.1
  flutter_riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  cupertino_icons: ^1.0.2
  auto_route: ^7.8.4
  device_preview: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  google_fonts: ^6.1.0
  toggle_switch: ^2.1.0
  auto_route_generator: ^7.3.2
  riverpod_generator: ^2.3.3
  freezed: ^2.4.5
  flutter_secure_storage: ^9.0.0
  firebase_auth: ^4.14.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.0
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_image.png
    - .env
  